# Array Manipulation – Assignment

Create an array containing values from 1 to 25.

In [2]:
import numpy as np

In [3]:
arr=np.arange(1,26)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


Convert a one-dimensional array of 25 elements into a 5 × 5 matrix.


In [4]:
arr=np.arange(25).reshape(5,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Insert a new element at a specific index in a one-dimensional array.

In [6]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
result=np.insert(arr,2,100)

In [8]:
result

array([  1,   2, 100,   3,   4,   5])

Insert a new row into a 2D matrix at the second row position.

In [10]:
arr=np.arange(1,11).reshape(5,2)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
new_row=[0,0]

In [14]:
np.insert(arr,2,new_row,axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 0,  0],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

Replace all occurrences of a specific value in an array with another value.

In [15]:
arr=np.array([1,2,3,4,5,6,7,8,1,2,3,4,1,2,3,2,1,3,2,4,2])


In [21]:
arr=np.unique(arr)

In [22]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
arr=np.array([1,5,63,52,9,26,85,34,15,19,13])
threshold=15
replacement=99
arr[arr>threshold]=99
print(arr)

[ 1  5 99 99  9 99 99 99 15 99 13]


Delete an element from an array at a specified index.

In [29]:
arr=np.arange(10,30).reshape(4,5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [33]:
result=np.delete(arr,7)

In [34]:
result

array([10, 11, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

Combine two one-dimensional arrays vertically.


In [42]:
arr=np.array([1,2,3,4]).reshape(-1,1)
print(arr)
arr1=np.array([5,6,7,8]).reshape(-1,1)
print(arr1)

[[1]
 [2]
 [3]
 [4]]
[[5]
 [6]
 [7]
 [8]]


Combine two 2D matrices horizontally (side by side).


In [43]:
arr=np.arange(1,21).reshape(4,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [44]:
arr1=np.arange(21,41).reshape(4,5)
print(arr1)

[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [47]:
result=np.hstack((arr,arr1))
print(result)

[[ 1  2  3  4  5 21 22 23 24 25]
 [ 6  7  8  9 10 26 27 28 29 30]
 [11 12 13 14 15 31 32 33 34 35]
 [16 17 18 19 20 36 37 38 39 40]]


Divide a one-dimensional array into equal parts.

In [50]:
arr=np.arange(6)

In [51]:
arr

array([0, 1, 2, 3, 4, 5])

In [53]:
result=np.split(arr,2)

In [54]:
result

[array([0, 1, 2]), array([3, 4, 5])]

Extract the last two rows from a matrix.

In [55]:
arr=np.arange(1,51).reshape(5,10)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [56]:
arr[-2:]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

Extract specific elements from different positions in a matrix without using loops.

In [58]:
arr = np.array([[10, 11, 12, 13, 14],
                [15, 16, 17, 18, 19],
                [20, 21, 22, 23, 24],
                [25, 26, 27, 28, 29]])
rows = [0, 1, 2, 3]
cols = [1, 3, 4, 0]
selected = arr[rows, cols]
print(selected)

[11 18 24 25]


Filter values in an array that lie between two given numbers.

In [59]:
arr = np.array([5, 10, 15, 20, 25, 30, 35])
filtered = arr[(arr >= 12) & (arr <= 28)]
print(filtered)


[15 20 25]


Add a smaller array to each row of a larger 2D array (broadcasting concept).

In [60]:
A = np.array([[10, 11, 12, 13, 14],
              [15, 16, 17, 18, 19],
              [20, 21, 22, 23, 24],
              [25, 26, 27, 28, 29]])

B = np.array([1, 2, 3, 4, 5])
C = A + B
print(C)

[[11 13 15 17 19]
 [16 18 20 22 24]
 [21 23 25 27 29]
 [26 28 30 32 34]]


Given a 2D NumPy matrix containing duplicate rows, remove all duplicate rows and return a matrix that contains only unique rows (without using loops).

In [61]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [1, 2, 3],
                [7, 8, 9],
                [4, 5, 6]])

unique_rows = np.unique(arr, axis=0)
print(unique_rows)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


Convert a 2D matrix into a one-dimensional array.

In [62]:

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

one_d = arr.flatten()
print("Flatten:", one_d)
one_d_ravel = arr.ravel()
print("Ravel:", one_d_ravel)

Flatten: [1 2 3 4 5 6 7 8 9]
Ravel: [1 2 3 4 5 6 7 8 9]


Convert a matrix into its transpose.

In [63]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
transpose1 = arr.T
print("Transpose using .T:\n", transpose1)
transpose2 = np.transpose(arr)
print("Transpose using np.transpose:\n", transpose2)

Transpose using .T:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose using np.transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


Repeat an array multiple times to create a larger array.

In [64]:
arr = np.array([1, 2, 3])
larger_arr = np.tile(arr, 3)
print(larger_arr)

[1 2 3 1 2 3 1 2 3]


Rotate the elements of an array by a given number of positions to the right.

In [65]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

rotated_matrix = np.roll(A, 3)
print(rotated_matrix)


[[7 8 9]
 [1 2 3]
 [4 5 6]]
