## Part A: Integer Indexing & Slicing

1. Integer Indexing & Negative Indexing
Input
- A = np.array([100, 200, 300, 400, 500])
Expected Output
- First two elements → [100, 200]
- Last three elements → [300, 400, 500]
- Middle element → 300

In [1]:
import numpy as np

In [2]:
arr=np.array([100,200,300,400,500])

In [8]:
print("first two elements -->",arr[:2])
print("last three elements -->",arr[-3:])
print("middle element -->",arr[len(arr)//2])

first two elements --> [100 200]
last three elements --> [300 400 500]
middle element --> 300


2. Slicing (Exclude First & Last)
- Input
- A = np.array([2, 4, 6, 8, 10, 12, 14])
- Expected Output
 [4, 6, 8, 10, 12]


In [9]:
A = np.array([2, 4, 6, 8, 10, 12, 14])
print(A[1:-1])

[ 4  6  8 10 12]


3. 2D Array Indexing & Slicing
- Input
- M = np.array([
   [10, 20, 30, 40],
   [50, 60, 70, 80],
   [90, 100, 110, 120]
])
- Expected Output
- Sub-matrix →
 [[20, 30], [60, 70]]


- Last row → [90, 100, 110, 120]


- First column → [10, 50, 90]




In [10]:
M = np.array([ [10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120] ])
M

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [19]:
print("Sub-Matrix:",M[0:2,1:3])
print("Last row:",M[-1])
print("First column:",M[:,0])

Sub-Matrix: [[20 30]
 [60 70]]
Last row: [ 90 100 110 120]
First column: [10 50 90]


Input
- A = np.array([1, 2, 3, 4, 5, 6, 7, 8])
- Expected Output
 [1, 4, 7]

In [21]:
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[::3])

[1 4 7]


## Part B: Boolean Indexing

5. Condition-Based Filtering
Input
- A = np.array([5, 12, 17, 3, 8, 20])
- Expected Output
- Values > 10 → [12, 17, 20]
- Values ≤ 8 → [5, 3, 8]

In [26]:
A = np.array([5, 12, 17, 3, 8, 20])
print(A[A>10])
print(A[A<=8])

[12 17 20]
[5 3 8]


6. Multiple Boolean Conditions
- Input
- A = np.array([10, 15, 20, 25, 30, 35])
- Expected Output
 [20, 25, 30, 35]

In [27]:
A = np.array([10, 15, 20, 25, 30, 35])
print(A[A>15])

[20 25 30 35]


7. Boolean Filtering + Counting
- Input
- A = np.array([3, -2, 0, 5, -7, 8])
- Expected Output
- Non-negative values → [3, 0, 5, 8]
Negative count → 2

In [30]:
A = np.array([3, -2, 0, 5, -7, 8])
count=np.sum(A[A<0])
print("Non negatice values -->",A[A>=0],"Negativve count -->",count)

Non negatice values --> [3 0 5 8] Negativve count --> -9


8. Boolean Replacement
- Input
- A = np.array([1, 2, 3, 4, 5, 6, 7])
- Expected Output
 [-1, 2, -1, 4, -1, 6, -1]

In [31]:
A = np.array([1, 2, 3, 4, 5, 6, 7])
result=np.where(A%2!=0,-1,A)
print(result)

[-1  2 -1  4 -1  6 -1]


## Part C: Fancy Indexing


9. Index List Selection
- Input
- A = np.array([11, 22, 33, 44, 55, 66])
- Expected Output
 [22, 44, 66]


In [36]:
A = np.array([11, 22, 33, 44, 55, 66])
result=A[np.where(A%2==0)]
print(result)

[22 44 66]


10. Rearranging Elements
- Input
 A = np.array([100, 200, 300, 400, 500])
- Expected Output
 [500, 300, 100]

In [42]:

A = np.array([100, 200, 300, 400, 500])
result = np.flip(A)[[0, 2, 4]]

print(result)


[500 300 100]


11. Fancy Indexing on 2D Array
- M = np.array([
   [1, 2, 3],
   [4, 5, 6],
   [7, 8, 9]
])
- Expected Output
 [1, 5, 9]

In [43]:
M = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
result=np.diag(M)

In [45]:
result

array([1, 5, 9])

12. Row Reordering
- Input
 Same matrix as above.
- Expected Output
[[7, 8, 9],
[1, 2, 3]]


In [46]:
M = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
first=M[-1]
second=M[0]

In [49]:
result=np.vstack((first,second))
result

array([[7, 8, 9],
       [1, 2, 3]])

## Part D: Boolean Indexing vs np.where()

13. Filtering vs Transforming
- Input
 A = np.array([4, 9, 2, 7, 12, 3])
- Expected Output
Boolean indexing → [9, 7, 12]
- np.where() → [0, 1, 0, 1, 1, 0]

In [54]:
A = np.array([4, 9, 2, 7, 12, 3])
result=A[A>5]
print(result)
result2=np.where(A>5,1,0)
print(result2)

[ 9  7 12]
[0 1 0 1 1 0]


14. Replace Negatives (Two Methods)
- Input
 A = np.array([-5, 10, -3, 8, -1])
- Expected Output
 [0, 10, 0, 8, 0]

In [57]:
A = np.array([-5, 10, -3, 8, -1])
result=np.where(A<0,0,A)
print(result)

[ 0 10  0  8  0]


15. Labeling Data with np.where()
- Input
 scores = np.array([45, 60, 30, 85, 90])
- Expected Output
- Filtered scores → [60, 85, 90]
- Labels → ["Fail", "Pass", "Fail", "Pass", "Pass"]

In [61]:
scores = np.array([45, 60, 30, 85, 90])
filter_score=scores[scores>55]
print("Filter score:",filter_score)
result=[]
for i in scores:
    if i<50:
        result.append('''Fail''')
    else:
        result.append("Pass")
print("Labels",result)

Filter score: [60 85 90]
Labels ['Fail', 'Pass', 'Fail', 'Pass', 'Pass']


## Part E: Broadcasting

16. Row-wise Broadcasting
- Input
- M = np.array([[1, 2, 3],
             [4, 5, 6]])
- A = np.array([10, 20, 30])
- Expected Output
- Addition:
[[11, 22, 33],
[14, 25, 36]]
- Subtraction:
[[-9, -18, -27],
[-6, -15, -24]]


In [62]:
M = np.array([[1, 2, 3], [4, 5, 6]])
A = np.array([10, 20, 30])

In [63]:
print(M)

[[1 2 3]
 [4 5 6]]


In [64]:
print(A)

[10 20 30]


In [65]:
print(M+A)

[[11 22 33]
 [14 25 36]]


In [66]:
print(M-A)

[[ -9 -18 -27]
 [ -6 -15 -24]]


- 17. Row Normalization
- Input
- M = np.array([[2, 4],
             [6, 8]])
- Expected Output
[[1, 2],
[3, 4]]


In [67]:
M = np.array([[2, 4], [6, 8]])

In [68]:
M

array([[2, 4],
       [6, 8]])

In [73]:
M//M[0,0]

array([[1, 2],
       [3, 4]])

18. Scalar Broadcasting
- Input
 A = np.array([10, 20, 30])
- Expected Output
 [15, 25, 35]


In [74]:
 A = np.array([10, 20, 30])+5

In [75]:
A

array([15, 25, 35])

19. Boolean vs np.where() on 2D Array
- Input
- M = np.array([[5, 10, 15],
             [20, 25, 30]])
- Expected Output
[[5, 10, 15],
[20, 20, 20]]


In [76]:
M = np.array([[5, 10, 15], [20, 25, 30]])
M

array([[ 5, 10, 15],
       [20, 25, 30]])

In [79]:
M[1]=20

In [80]:
M

array([[ 5, 10, 15],
       [20, 20, 20]])

20. Broadcasting Concept Check
- Input
- M = np.array([[1, 2],
             [3, 4],
             [5, 6]])
- A = np.array([10, 20])
- Expected Output
[[11, 22],
[13, 24],
[15, 26]]


In [81]:
M = np.array([[1, 2], [3, 4], [5, 6]])
A = np.array([10, 20])

In [82]:
print(M)

[[1 2]
 [3 4]
 [5 6]]


In [83]:
print(A)

[10 20]


In [84]:
print(M+A)

[[11 22]
 [13 24]
 [15 26]]
