In [2]:
import numpy as np

In [3]:
data=np.genfromtxt("C:\\Users\\srava_kv\\customer details\\customer_purchases.csv",delimiter=",",encoding=None,dtype=None,names=True)

In [4]:
data

array([('01-08-2024', 101, 150.5 ), ('01-08-2024', 102, 200.  ),
       ('01-08-2024', 103, 350.75), ('02-08-2024', 101, 120.  ),
       ('02-08-2024', 104,  80.  ), ('02-08-2024', 105, 500.  ),
       ('03-08-2024', 101,  90.5 ), ('03-08-2024', 102, 240.  ),
       ('03-08-2024', 103, 190.25), ('03-08-2024', 104, 220.  ),
       ('04-08-2024', 101, 110.  ), ('04-08-2024', 105, 300.  ),
       ('04-08-2024', 102, 175.  ), ('05-08-2024', 103, 150.  ),
       ('05-08-2024', 104, 330.  ), ('06-08-2024', 105, 100.  ),
       ('06-08-2024', 101,  80.  ), ('06-08-2024', 103, 290.5 ),
       ('06-08-2024', 102, 220.  ), ('07-08-2024', 101,  60.  ),
       ('07-08-2024', 102, 310.  ), ('07-08-2024', 105, 400.  ),
       ('08-08-2024', 101,  95.5 ), ('08-08-2024', 104, 150.  ),
       ('09-08-2024', 103, 275.  ), ('09-08-2024', 102, 180.  ),
       ('09-08-2024', 105, 220.  ), ('10-08-2024', 104, 180.  ),
       ('10-08-2025', 103, 305.  ), ('10-08-2024', 101, 140.  ),
       ('11-08-2024', 106

In [5]:
unique_data=np.unique(data["CustomerID"])

In [6]:
print(unique_data)

[101 102 103 104 105 106]


In [7]:
total_amount_spend_customer={}

In [8]:
for customer in unique_data:
    total_amount_spend_customer[customer]=np.sum(data[data["CustomerID"]==customer]["AmountSpent"])

In [9]:
total_amount_spend_customer

{np.int64(101): np.float64(846.5),
 np.int64(102): np.float64(1325.0),
 np.int64(103): np.float64(1561.5),
 np.int64(104): np.float64(960.0),
 np.int64(105): np.float64(1520.0),
 np.int64(106): np.float64(240.0)}

In [10]:
unique_dates=np.unique(data["Date"])

In [11]:
unique_dates

array(['01-08-2024', '02-08-2024', '03-08-2024', '04-08-2024',
       '05-08-2024', '06-08-2024', '07-08-2024', '08-08-2024',
       '09-08-2024', '10-08-2024', '10-08-2025', '11-08-2024'],
      dtype='<U10')

In [12]:
daily_sales=np.zeros(unique_dates.size)

In [13]:
daily_sales

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
for i,date in enumerate(unique_dates):
    daily_sales[i]=np.sum(data[data["Date"]==date]["AmountSpent"])

In [15]:
daily_sales

array([701.25, 700.  , 740.75, 585.  , 480.  , 690.5 , 770.  , 245.5 ,
       675.  , 320.  , 305.  , 240.  ])

In [16]:
highest_sale=np.argmax(daily_sales)

In [17]:
print(highest_sale)

6


In [18]:
highest_sales_day=unique_dates[highest_sale]

In [19]:
print(highest_sales_day)

07-08-2024


In [21]:
import csv

with open("Purchase_Analysis.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["CustomerID", "Total_Amount_Spent"])
    for id, total in total_amount_spend_customer.items():
        writer.writerow([id, total])
    writer.writerow([])  # Blank row
    writer.writerow(["Date", "Total_Sales"])
    for date, sales in zip(unique_dates, daily_sales):
        writer.writerow([date, sales])
